name: MlchsUtil
version: 1.2.0
main: io.github.koobie2.mlchsutil.MlchsUtil
description: Utilities for the mlchs server.
author: koobie2
website: https://papermc.io
api-version: '1.21.4'
commands:
  jail:
    description: Jails a player, defaults to the sender if no player is specified. Unjails them after a specified time if time is specified.
    usage: /<command> player time
  unjail:
    description: Unjail a player if they are already jailed.
    usage: /<command> player
  playtime:
    description: Display the players playtime if player is specified. Otherwise display the senders playtime if sender is a player.
    usage: /<command> player
  topplaytime:
    description: Display a leaderboard of playtime. if amount is specified only show amount players.
    usage: /<command> amount
  setplaytime:
    description: Set the players time.
    usage: /<command> player hours minutes seconds