name: MlchsUtil
version: 1.0.0
main: io.github.koobie2.mlchsutil.MlchsUtil
description: Utilities for the mlchs server.
author: koobie2
website: https://papermc.io
api-version: '1.21.4'
commands:
  jail:
    description: Jails a player, defaults to the sender if no player is specified. Unjails them after a specified time if time is specified.
    usage: /<command> player time
  unjail:
    description: Unjail a player if they are already jailed.
    usage: /<command> player